

module.exports ={
    
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",

    SAVE_SHIPPING_INFO : "SAVE_SHIPPING_INFO",

    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}