module.exports = {
    CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL : "CREATE_ORDER_FAIL",

    GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    GET_ORDER_FAIL : "GET_ORDER_FAIL",


    CLEAR_ERRORS: "CLEAR_ERRORS"
}