

module.exports ={
    ALL_PRODUCT_FAIL : "ALL_PRODUCT_FAIL",
    ALL_PRODUCT_SUCCESS : "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_REQUEST : "ALL_PRODUCT_REQUEST",
    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}