

module.exports ={
    ALL_PRODUCT_FAIL : "ALL_PRODUCT_FAIL",
    ALL_PRODUCT_SUCCESS : "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_REQUEST : "ALL_PRODUCT_REQUEST",

    PRODUCT_DETAILS_FAIL : "PRODUCT_DETAILS_FAIL",
    PRODUCT_DETAILS_SUCCESS : "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_REQUEST : "PRODUCT_DETAILS_REQUEST",

    NEW_REVIEW_REQUEST: "NEW_REVIEW_REQUEST",
    NEW_REVIEW_SUCCESS: "NEW_REVIEW_SUCCESS",
    NEW_REVIEW_FAIL: "NEW_REVIEW_FAIL",
    NEW_REVIEW_RESET: "NEW_REVIEW_RESET",

    ADMIN_PRODUCTS_REQUEST: "ADMIN_PRODUCTS_REQUEST",
    ADMIN_PRODUCTS_SUCCESS: "ADMIN_PRODUCTS_SUCCESS",
    ADMIN_PRODUCTS_FAIL: "ADMIN_PRODUCTS_FAIL",

    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}