

module.exports ={
    ALL_PRODUCT_FAIL : "ALL_PRODUCT_FAIL",
    ALL_PRODUCT_SUCCESS : "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_REQUEST : "ALL_PRODUCT_REQUEST",

    PRODUCT_DETAILS_FAIL : "PRODUCT_DETAILS_FAIL",
    PRODUCT_DETAILS_SUCCESS : "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_REQUEST : "PRODUCT_DETAILS_REQUEST",

    NEW_REVIEW_REQUEST: "NEW_REVIEW_REQUEST",
    NEW_REVIEW_SUCCESS: "NEW_REVIEW_SUCCESS",
    NEW_REVIEW_FAIL: "NEW_REVIEW_FAIL",
    NEW_REVIEW_RESET: "NEW_REVIEW_RESET",

    ADMIN_PRODUCTS_REQUEST: "ADMIN_PRODUCTS_REQUEST",
    ADMIN_PRODUCTS_SUCCESS: "ADMIN_PRODUCTS_SUCCESS",
    ADMIN_PRODUCTS_FAIL: "ADMIN_PRODUCTS_FAIL",

    NEW_PRODUCT_REQUEST: "NEW_PRODUCT_REQUEST",
    NEW_PRODUCT_SUCCESS: "NEW_PRODUCT_SUCCESS",
    NEW_PRODUCT_FAIL: "NEW_PRODUCT_FAIL",
    NEW_PRODUCT_RESET: "NEW_PRODUCT_RESET",

    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",
    DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET",

    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",
    UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",

    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}