

module.exports ={
    LOGIN_FAIL : "LOGIN_FAIL",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_REQUEST : "LOGIN_REQUEST",

    REGISTER_USER_FAIL : "REGISTER_USER_FAIL",
    REGISTER_USER_SUCCESS : "REGISTER_USER_SUCCESS",
    REGISTER_USER_REQUEST : "REGISTER_USER_REQUEST",

    LOAD_USER_FAIL : "LOAD_USER_FAIL",
    LOAD_USER_SUCCESS : "LOAD_USER_SUCCESS",
    LOAD_USER_REQUEST : "LOAD_USER_REQUEST",

    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",

    UPDATE_PROFILE_FAIL : "UPDATE_PROFILE_FAIL",
    UPDATE_PROFILE_SUCCESS : "UPDATE_PROFILE_SUCCESS",
    UPDATE_PROFILE_REQUEST : "UPDATE_PROFILE_REQUEST",
    UPDATE_PROFILE_RESET : "UPDATE_PROFILE_RESET",

    UPDATE_PASSWORD_FAIL : "UPDATE_PASSWORD_FAIL",
    UPDATE_PASSWORD_SUCCESS : "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_REQUEST : "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_RESET : "UPDATE_PASSWORD_RESET",

    FORGOT_PASSWORD_FAIL : "FORGOT_PASSWORD_FAIL",
    FORGOT_PASSWORD_SUCCESS : "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_REQUEST : "FORGOT_PASSWORD_REQUEST",

    RESET_PASSWORD_FAIL : "RESET_PASSWORD_FAIL",
    RESET_PASSWORD_SUCCESS : "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_REQUEST : "RESET_PASSWORD_REQUEST",

    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}