

module.exports ={
    LOGIN_FAIL : "LOGIN_FAIL",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_REQUEST : "LOGIN_REQUEST",

    REGISTER_USER_FAIL : "REGISTER_USER_FAIL",
    REGISTER_USER_SUCCESS : "REGISTER_USER_SUCCESS",
    REGISTER_USER_REQUEST : "REGISTER_USER_REQUEST",

    CLEAR_ERRORS : "CLEAR_ERRORS",
        
}